<?php

// Data functions for table clients

// This script and data application were generated by AppGini 4.50
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function clients_insert(){
	global $Translation;

	if($_GET['insert_x']){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('clients');
	if(!$arrPerm[1]){
		return 0;
	}

	$data['name'] = makeSafe($_POST['name']);
	$data['contact'] = makeSafe($_POST['contact']);
	$data['address'] = makeSafe($_POST['address']);
	$data['phone'] = makeSafe($_POST['phone']);
	$data['email'] = makeSafe($_POST['email']);
	$data['website'] = makeSafe($_POST['website']);
	$data['comments'] = makeSafe($_POST['comments']);

	// hook: clients_before_insert
	if(function_exists('clients_before_insert')){
		$args=array();
		if(!clients_before_insert($data, getMemberInfo(), $args)){ return FALSE; }
	}

	sql('insert into `clients` set `name`=' . (($data['name'] != '') ? "'{$data['name']}'" : 'NULL') . ', `contact`=' . (($data['contact'] != '') ? "'{$data['contact']}'" : 'NULL') . ', `address`=' . (($data['address'] != '') ? "'{$data['address']}'" : 'NULL') . ', `phone`=' . (($data['phone'] != '') ? "'{$data['phone']}'" : 'NULL') . ', `email`=' . (($data['email'] != '') ? "'{$data['email']}'" : 'NULL') . ', `website`=' . (($data['website'] != '') ? "'{$data['website']}'" : 'NULL') . ', `comments`=' . (($data['comments'] != '') ? "'{$data['comments']}'" : 'NULL'));
	$recID=mysql_insert_id();

	// hook: clients_after_insert
	if(function_exists('clients_after_insert')){
		$data['selectedID']=$recID;
		$args=array();
		if(!clients_after_insert($data, getMemberInfo(), $args)){ return; }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='clients', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'");

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function clients_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('clients');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='clients' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='clients' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return FALSE;
	}

	// hook: clients_before_delete
	if(function_exists('clients_before_delete')){
		$args=array();
		if(!clients_before_delete($selected_id, $skipChecks, getMemberInfo(), $args)){ return FALSE; }
	}

	// child table: invoices
	$res = sql("select `id` from `clients` where `id`='$selected_id'");
	$id = mysql_fetch_row($res);
	$rires = sql("select count(1) from `invoices` where `client`='".addslashes($id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "invoices", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "invoices", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='clients_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='clients_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `clients` where `id`='$selected_id'");

	// hook: clients_after_delete
	if(function_exists('clients_after_delete')){
		$args=array();
		clients_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='clients' and pkValue='$selected_id'");
}

function clients_update($selected_id){
	global $Translation;

	if($_GET['update_x']){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('clients');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='clients' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='clients' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return;
	}

	$data['name'] = makeSafe($_POST['name']);
	$data['contact'] = makeSafe($_POST['contact']);
	$data['address'] = makeSafe($_POST['address']);
	$data['phone'] = makeSafe($_POST['phone']);
	$data['email'] = makeSafe($_POST['email']);
	$data['website'] = makeSafe($_POST['website']);
	$data['comments'] = makeSafe($_POST['comments']);
	$data['selectedID']=makeSafe($selected_id);

	// hook: clients_before_update
	if(function_exists('clients_before_update')){
		$args=array();
		if(!clients_before_update($data, getMemberInfo(), $args)){ return FALSE; }
	}

	sql('update `clients` set `name`=' . (($data['name'] != '') ? "'{$data['name']}'" : 'NULL') . ', `contact`=' . (($data['contact'] != '') ? "'{$data['contact']}'" : 'NULL') . ', `address`=' . (($data['address'] != '') ? "'{$data['address']}'" : 'NULL') . ', `phone`=' . (($data['phone'] != '') ? "'{$data['phone']}'" : 'NULL') . ', `email`=' . (($data['email'] != '') ? "'{$data['email']}'" : 'NULL') . ', `website`=' . (($data['website'] != '') ? "'{$data['website']}'" : 'NULL') . ', `comments`=' . (($data['comments'] != '') ? "'{$data['comments']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'");

	// hook: clients_after_update
	if(function_exists('clients_after_update')){
		$args=array();
		if(!clients_after_update($data, getMemberInfo(), $args)){ return FALSE; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='clients' and pkValue='".makeSafe($selected_id)."'");

}

function clients_form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;


	// mm: get table permissions
	$arrPerm=getTablePermissions('clients');
	if(!$arrPerm[1] && $selected_id==""){ return ""; }

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='clients' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='clients' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `clients` where `id`='".makeSafe($selected_id)."'");
		$row = mysql_fetch_array($res);
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if(($_POST['dvprint_x'] || $_GET['dvprint_x']) && $selected_id){
		$templateCode=@implode('', @file('./templates/clients_templateDVP.html'));
		$dvprint=true;
	}else{
		$templateCode=@implode('', @file('./templates/clients_templateDV.html'));
		$dvprint=false;
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Client data', $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id){ // allow insert and no record selected?
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<input type="image" src="insert.gif" name="insert" alt="' . $Translation['add new record'] . '" onclick="return validateData();">', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		$templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<input type="image" src="print.gif" vspace="1" name="dvprint" id="dvprint" alt="' . $Translation['printer friendly view'] . '" onclick="document.myform.reset(); return true;" style="margin-bottom: 20px;">', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<input type="image" src="update.gif" vspace="1" name="update" alt="' . $Translation['update record'] . '" onclick="return validateData();">', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

			// set records to read only if user can't insert new records
			if(!$arrPerm[1]){
				$jsReadOnly.="\n\n\tif(document.getElementsByName('id').length){ document.getElementsByName('id')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('name').length){ document.getElementsByName('name')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('contact').length){ document.getElementsByName('contact')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('address').length){ document.getElementsByName('address')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('phone').length){ document.getElementsByName('phone')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('email').length){ document.getElementsByName('email')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('website').length){ document.getElementsByName('website')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementById('websiteEditLink')){ document.getElementById('websiteEditLink').style.display='none'; }\n";

				$noUploads=true;
			}
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<input type="image" src="delete.gif" vspace="1" name="delete" alt="' . $Translation['delete record'] . '" onClick="return confirm(\'' . $Translation['are you sure?'] . '\');">', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt=\"" . $Translation['deselect record'] . "\" onclick=\"document.myform.reset(); return true;\">", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? "<input type=image src=cancel.gif vspace=1 name=deselect alt=\"" . $Translation['deselect record'] . "\" onclick=\"document.myform.reset(); return true;\">" : ''), $templateCode);
	}

	// process combos

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(contact)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(address)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(phone)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(website)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(comments)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(name)%%>', htmlspecialchars($row['name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(contact)%%>', htmlspecialchars($row['contact'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(address)%%>', htmlspecialchars($row['address'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(phone)%%>', htmlspecialchars($row['phone'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', htmlspecialchars($row['email'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(website)%%>', htmlspecialchars($row['website'], ENT_QUOTES), $templateCode);
		if($AllowUpdate || $AllowInsert){
			$templateCode=str_replace('<%%HTMLAREA(comments)%%>', '<textarea name="comments" id="comments" cols="50" rows="5" class="TextBox">'.htmlspecialchars($row['comments'], ENT_QUOTES).'</textarea>', $templateCode);
		}else{
			$templateCode=str_replace('<%%HTMLAREA(comments)%%>', $row['comments'], $templateCode);
		}
		$templateCode=str_replace('<%%VALUE(comments)%%>', $row['comments'], $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(contact)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(address)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(phone)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(website)%%>', '', $templateCode);
		$templateCode=str_replace('<%%HTMLAREA(comments)%%>', '<textarea name="comments" id="comments" cols="50" rows="5" class="TextBox"></textarea>', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);
	// hide links to inaccessible tables
	$templateCode.="\n\n<script>\n";
	$arrTables=getTableList();
	foreach($arrTables as $name=>$caption){
		$templateCode.="\tif(document.getElementById('".$name."_link')!=undefined){\n";
		$templateCode.="\t\tdocument.getElementById('".$name."_link').style.visibility='visible';\n";
		$templateCode.="\t}\n";
		for($i=1; $i<10; $i++){
			$templateCode.="\tif(document.getElementById('".$name."_plink$i')!=undefined){\n";
			$templateCode.="\t\tdocument.getElementById('".$name."_plink$i').style.visibility='visible';\n";
			$templateCode.="\t}\n";
		}
	}

	$templateCode.=$jsReadOnly;

	if(!$selected_id){
		$templateCode.="\n\tif(document.getElementById('emailEdit')){ document.getElementById('emailEdit').style.display='inline'; }";
		$templateCode.="\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }";
		$templateCode.="\n\tif(document.getElementById('websiteEdit')){ document.getElementById('websiteEdit').style.display='inline'; }";
		$templateCode.="\n\tif(document.getElementById('websiteEditLink')){ document.getElementById('websiteEditLink').style.display='none'; }";
	}

	$templateCode.="\n\tfunction validateData(){";
	$templateCode.="\n\t\treturn true;";
	$templateCode.="\n\t}";
	$templateCode.="\n</script>\n";


	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="window.onload=function(){";


	$templateCode.="}";
	$templateCode.="</script>";

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: clients_dv
	if(function_exists('clients_dv')){
		$args=array();
		clients_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>