		<!-- Add footer template above here -->
		<div class="displayOnly" style="text-align: center; font-size: 10px; font-family: arial; margin-top: 20px;">This application was automatically generated by <a href="http://bigprof.com/appgini/?r=invoicing">AppGini 4.50</a></div>
		</body>
	</html>