<?php
// This script and data application were generated by AppGini 4.50
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	$d=dirname(__FILE__);
	include("$d/defaultLang.php");
	include("$d/language.php");
	include("$d/lib.php");
	@include("$d/hooks/invoice_items.php");
	include("$d/invoice_items_dml.php");
	// mm: can the current member access this page?
	$perm=getTablePermissions('invoice_items');
	if(!$perm[0]){
		echo StyleSheet();
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		echo '<script language="javaScript">setInterval("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "invoice_items";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(
		"`invoice_items`.`id`" => "ID",
		"`invoices1`.`code` /* Invoice */" => "Invoice",
		"`invoice_items`.`item`" => "Item",
		"FORMAT(`invoice_items`.`unit_price`, 2)" => "Unit price",
		"FORMAT(`invoice_items`.`qty`, 3)" => "Qty",
		"FORMAT(`invoice_items`.`tax`, 2)" => "Tax %",
		"FORMAT(`invoice_items`.`price`, 2)" => "Price"
	);
	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(
		"`invoice_items`.`id`" => "ID",
		"`invoices1`.`code` /* Invoice */" => "Invoice",
		"`invoice_items`.`item`" => "Item",
		"FORMAT(`invoice_items`.`unit_price`, 2)" => "Unit price",
		"FORMAT(`invoice_items`.`qty`, 3)" => "Qty",
		"FORMAT(`invoice_items`.`tax`, 2)" => "Tax %",
		"FORMAT(`invoice_items`.`price`, 2)" => "Price"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(
		"`invoice_items`.`id`" => "ID",
		"`invoices1`.`code` /* Invoice */" => "Invoice",
		"`invoice_items`.`item`" => "Item",
		"`invoice_items`.`unit_price`" => "Unit price",
		"`invoice_items`.`qty`" => "Qty",
		"`invoice_items`.`tax`" => "Tax %",
		"`invoice_items`.`price`" => "Price"
	);

	$x->QueryFrom="`invoice_items` LEFT JOIN `invoices` as invoices1 ON `invoice_items`.`invoice`=invoices1.`id` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "invoice_items_view.php";
	$x->RedirectAfterInsert = "invoice_items_view.php?SelectedID=#ID#";
	$x->TableTitle = "Invoice items";
	$x->PrimaryKey = "`invoice_items`.`id`";

	$x->ColWidth   = array(350, 80, 60, 60, 80);
	$x->ColCaption = array("Item", "Unit price", "Qty", "Tax %", "Price");
	$x->ColNumber  = array(3, 4, 5, 6, 7);

	$x->Template = 'templates/invoice_items_templateTV.html';
	$x->SelectedTemplate = 'templates/invoice_items_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	if($perm[2]==1){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `invoice_items`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='invoice_items' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `invoice_items`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='invoice_items' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`invoice_items`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}

	// handle date sorting correctly
	// end of date sorting handler

	// hook: invoice_items_init
	$render=TRUE;
	if(function_exists('invoice_items_init')){
		$args=array();
		$render=invoice_items_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		$sumQuery="select FORMAT(sum(`invoice_items`.`price`), 2) from ".$x->QueryFrom.' '.$x->QueryWhere;
		$sumStyle='color: green; text-align: right; font-weight: normal;';
		$res=sql($sumQuery);
		if($row=mysql_fetch_row($res)){
			$sumRow ="<tr>";
			$sumRow.="<td class=\"TableHeader\" style=\"$sumStyle\"><b>&sum;</b></td>";
			$sumRow.="<td class=\"TableHeader\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableHeader\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableHeader\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableHeader\" style=\"$sumStyle\">&nbsp;</td>";
			$sumRow.="<td class=\"TableHeader\" style=\"$sumStyle\">&nbsp;$row[0]</td>";
			$sumRow.="</tr>";

			$x->HTML=str_replace("<!-- tv data below -->", '', $x->HTML);
			$x->HTML=str_replace("<!-- tv data above -->", $sumRow, $x->HTML);
		}
	}

	// hook: invoice_items_header
	$headerCode='';
	if(function_exists('invoice_items_header')){
		$args=array();
		$headerCode=invoice_items_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include("$d/header.php"); 
	}else{
		ob_start(); include("$d/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: invoice_items_footer
	$footerCode='';
	if(function_exists('invoice_items_footer')){
		$args=array();
		$footerCode=invoice_items_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include("$d/footer.php"); 
	}else{
		ob_start(); include("$d/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>